---
# - name: Uninstall old version of docker
#   tags: 'docker'
#   become: yes
#   apt:
#     name: ['docker','docker-engine','docker.io']
#     state: absent

- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install docker-py
  become: yes
  pip:
    name: ['docker-py']
    state: latest

- name: docker | build image
  docker_image:
    name: frontend
    tag: v001
    path: /home/ubuntu/COMP90024/frontend
    state: present

- name: docker | run container
  docker:
    name: frontend_site_{{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}
    image: "frontend:v001"
    state: reloaded
    publish_all_ports: yes

  # {{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}