---
#############################################
#              Common vars                  #
#############################################
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal
instance_flavor: uom.mse.2c9g
instance_image: 0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5 # Ubuntu 16.04
instance_key_name: NectarGroup # ssh private key
project_working_directory: /home/xuwang/CCC-COMP90024

#############################################
#             Security group                #
#############################################
security_groups:
  - name: web-security-group
    description: "security group for web server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: spider-security-group
    description: "security group for spider server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: machine-learning-security-group
    description: "security group for machine learning server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: database-security-group
    description: "security group for database server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0


#############################################
#                Instance                   #
#############################################
instances:
  - name: Database
    security_groups: database-security-group
    volume_ids: '{{ Database_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db1
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: WebServer
    security_groups: web-security-group
    volume_ids: '{{ WebServer_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db2
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: Spider
    security_groups: spider-security-group
    volume_ids: '{{ Spider_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db3
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: MachineLearning
    security_groups: machine-learning-security-group
    volume_ids: '{{ MachineLearning_volumes|default([]) }}'
    volumes:
      - vol_name: volume_ml
        vol_size: 10
        device: /dev/vdb
        mountpoint: /data
