---
- name: add proxy to enviroments
  become: yes
  lineinfile:
    line: "http_proxy=\"{{ proxy_address }}\"\nhttps_proxy=\"{{ proxy_address }}\"\nftp_proxy=\"{{ proxy_address }}\""
    dest: /etc/environment

- name: make proxy available for current session
  become: yes
  shell: echo 'add proxy configuration success'
  environment:
    http_proxy: "{{ proxy_address }}"
    https_proxy: "{{ proxy_address }}"
    ftp_proxy: "{{ proxy_address }}"

# add proxy configuration

- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
# apt-get upgrade; apt-get update

- name: install dependencies
  become: yes
  apt:
    name: ['vim','unzip','git','xfsprogs','python-pip','apt-transport-https','ca-certificates','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- include_tasks: docker.yaml
