---
- name: pull latest code from git
  command: chdir={{ remote_working_directory }} git pull

- name: copy compose file to server
  template:
    src: spider-docker-compose.yaml.j2
    dest: '/home/ubuntu/docker-compose.yaml'
    owner: ubuntu
    group: ubuntu

- name: docker compose down
  become: yes
  command: docker-compose down --rmi all

- name: docker compose rm -f
  become: yes
  command: docker-compose rm -f

- name: docker compose pull
  become: yes
  command: docker-compose pull

- name: start docker-compose
  become: yes
  command: docker-compose up --build -d
