---
- name: Make file system
  filesystem:
    fstype: ext4
    dev: "{{ item.device }}"
  when: item.device is defined
  loop: "{{ outer_item.volumes }}"

- name: Check folders
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  loop: "{{ outer_item.volumes }}"

- name: Create directory
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stats.exists == false
  loop: "{{ directory_stats.results }}"

- name: Mount device
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: ext4
    state: mounted
  when: item.device is defined
  loop: "{{ outer_item.volumes }}"