---
- name: ngrok | download
  become: yes
  get_url:
    url: "{{ ngrok_download }}"
    dest: "{{ ngrok_path_download_tmp }}/ngrok.zip"

- name: ngrok | unzip
  become: yes
  unarchive:
    src: "{{ ngrok_path_download_tmp }}/ngrok.zip"
    dest: "{{ ngrok_path_download_tmp }}"
    creates: "{{ ngrok_path_download_tmp }}/ngrok"
    copy: no

- name: ngrok | install binary
  become: yes
  command: "mv ./ngrok {{ ngrok_path_bin }}"
  args:
    chdir: "{{ ngrok_path_download_tmp }}"
    creates: "{{ ngrok_path_bin }}"

- name: ngrok | set binary permissions
  become: yes
  file:
    path: "{{ ngrok_path_bin }}"
    mode: 0755
    state: file

- name: change docker proxy | step 1
  become: yes
  command: mkdir /etc/systemd/system/docker.service.d

- name: change docker proxy | step 2
  become: yes
  copy:
    content: "[Service]\nEnvironment=\"HTTP_PROXY={{ proxy_address }}\""
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf

- name: change docker proxy | step 3
  become: yes
  command: systemctl daemon-reload

- name: change docker proxy | step 4
  become: yes
  command: systemctl restart docker