---
- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: couchdb-cluster

- hosts: instance1
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-webserver
    - role: restart-docker-compose

- hosts: instance2
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-backend-and-spider
    - role: restart-docker-compose

- hosts: instance3
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-nlp
    - role: restart-docker-compose

- hosts: instance4
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-ml-server
    - role: restart-docker-compose
