- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: common
    - role: show-images
    # - role: openstack-volume
    - role: create-security-groups
    - role: create-instances
    # - role: openstack-volume-snapshot